version: '3.2'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - type: bind
        source: ./schemas/
        target: /docker-entrypoint-initdb.d/
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password

  api:
    build: ./../backend
    restart: always
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql

  ui:
    build: ./../frontend
    restart: always
    ports:
      - "8080:8080"
    links:
      - api
    depends_on:
      - api

  
